name: Build multi-arch all-in-one

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
        - name: linux
          task: GOOS=linux GOARCH=amd64 $(MAKE) build-all-in-one
        - name: system/390
          task: GOOS=linux GOARCH=s390x $(MAKE) build-all-in-one
        - name: arm
          task: GOOS=linux GOARCH=arm64 $(MAKE) build-all-in-one
    name: build all-in-one for ${{ matrix.platform.name }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Fetch git tags
      run: |
        git fetch --prune --unshallow --tags

    - uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Export BRANCH variable
      uses: ./.github/actions/setup-branch

    - name: Install tools
      run: make install-ci

    - name: Build All-in-one
      run: make ${{ matrix.platform.task }}
  
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1 
      with:
        username: kunluibm
        password: cc6d5ad8-6b6c-4ec3-8569-0942a007b916
    - name: "build the image"
      run: docker buildx build --push --progress=plain --platform=linux/arm64,linux/amd64,linux/s390x --file cmd/all-in-one/Dockerfile --tag kunluibm/jaegertest:latest cmd/all-in-one
