name: Build multi-arch all-in-one

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build-docker-image:
    #needs: build-binaries
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 80:80
    steps:
    - uses: actions/checkout@v2.3.4

    - uses: docker/setup-qemu-action@v1

    - uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host

    - uses: docker/login-action@v1 
      with:
        username: kunluibm
        password: cc6d5ad8-6b6c-4ec3-8569-0942a007b916

    - name: "build the image"
      run: bash scripts/build-all-in-one-image-multiarch.sh
