name: Build multi-arch all-in-one

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
        - name: linux
          task: GOOS=linux GOARCH=amd64 $(MAKE) build-all-in-one
        - name: system/390
          task: GOOS=linux GOARCH=s390x $(MAKE) build-all-in-one
        - name: arm
          task: GOOS=linux GOARCH=arm64 $(MAKE) build-all-in-one
    name: build all-in-one for ${{ matrix.platform.name }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Fetch git tags
      run: |
        git fetch --prune --unshallow --tags

    - uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Export BRANCH variable
      uses: ./.github/actions/setup-branch

    - name: Install tools
      run: make install-ci

    - name: Build All-in-one
      run: make ${{ matrix.platform.task }}
    
    - name: Upload artifacts
      use: actions/upload-artifact@v2
      with: 
        name: all-in-one-linux
        path: ./cmd/all-in-one/all-in-one-linux-*
        

  build-docker-image:
    needs: build-binaries
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
    - uses: actions/checkout@v2.3.4

    - uses: docker/setup-qemu-action@v1

    - uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host

    - uses: docker/login-action@v1 
      with:
        username: kunluibm
        password: cc6d5ad8-6b6c-4ec3-8569-0942a007b916
    
    - name: "build the image"
      run: bash scripts/build-all-in-one-image-multiarch.sh
