name: Build multi-arch docker images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker-images:
    runs-on: ubuntu-latest
    
    services:
      registry:
        image: registry:2
        ports:
          - 5005:5005

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Fetch git tags
      run: |
        git fetch --prune --unshallow --tags

    - uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - uses: actions/setup-node@v2.1.5
      with:
        node-version: '10'

    - name: Export BRANCH variable
      uses: ./.github/actions/setup-branch

    - name: Install tools
      run: make install-ci
    
    - name: Build binaries
      id: build-binaries
      run: make build-all-platforms

    - uses: docker/setup-qemu-action@v1

    - uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host
    
    - uses: docker/login-action@v1 
      with:
        username: kunlu20
        password: 4f850c08-489a-4b71-9deb-eb75138258ad
  
    - name: Build multidock docker images
      run: make docker-images-jaeger-backend-multiarch
